version: '3'

vars:
  BACKEND_PORT: 3000
  VITE_PORT: 3001
  FLUTTER_PORT: 3002

tasks:
  backend:serve: cd backend && PORT={{.BACKEND_PORT}} node index.js
  backend:tunnel: ngrok http --subdomain=edsm {{.BACKEND_PORT}}
  vite:serve: cd frontend && npx -y vite --port={{.VITE_PORT}}
  vite:tunnel: ngrok http --subdomain=edsm-vite {{.VITE_PORT}}
  flutter:serve: cd mobile && flutter build web && npx -y serve -l {{.FLUTTER_PORT}} build/web
  flutter:watch: cd mobile && npx -y nodemon -w lib -e 'dart' -x 'flutter build web && npx -y serve -l {{.FLUTTER_PORT}} build/web'
  flutter:tunnel: ngrok http --subdomain=edsm-flutter {{.FLUTTER_PORT}}
  serve: > 
    tmux new-session 'task backend:serve' \; 
    split-window -h 'task vite:serve' \; 
    split-window -h  \;
    send-keys 'task flutter:serve' Enter \;
    select-layout even-horizontal \;
    select-pane -t 0 \;
    split-window -v 'task backend:tunnel' \;
    select-pane -t 2 \;
    split-window -v 'task vite:tunnel' \;
    select-pane -t 4 \;
    split-window -v 'task flutter:tunnel' \;
    select-pane -t 4 \;
